def determine_exit_code(exception: Exception) -> int:
    """
    Determine the exit code based on the exception that was thrown

    :param exception: The exception that was thrown
    :return: The exit code
    """
    return 1
